### ISSUE TITLE
Unity project is broken

### ISSUE THREAD

**Issue by yangyanzhan** [CapsuleEndoscope/VirtualCapsuleEndoscopy#1]
Hi, I've loaded the project into unity. However, several assets are missing from the project. Could you tell me how to fix this issue?

![image](https://user-images.githubusercontent.com/5428667/108987201-f96d5f80-76cd-11eb-805b-018284065771.png)

**Comment by C-H-Chien** [comment]
Hi, I have the same problem. I loaded the scene from VR-Caps-Unity/Assets/Scenes/Record_scene.unity but it shows like the following figure:

![Screenshot from 2021-03-18 22-49-02](https://user-images.githubusercontent.com/43362125/111724963-8a060e00-883c-11eb-9b69-89b457d662df.png)

Did you solve the problem @yangyanzhan ?

**Comment by C-H-Chien** [comment]
I emailed to the author of the paper and they kindly updated their Unity project. Now the Unity project can be run normally!

**Comment by hamidrexa** [comment]
you should install SOFA library properly

**Comment by xx674967** [comment]
Hi @C-H-Chien , I have the same problem as you. The current version should be updated by the author after you encountered the problem. Do you have any solution? Looking forward to your reply  ^^

**Comment by C-H-Chien** [comment]
> Hi @C-H-Chien , I have the same problem as you. The current version should be updated by the author after you encountered the problem. Do you have any solution? Looking forward to your reply ^^

Hi! It's been over a year since my last try but as far as I remember the authors have updated their Unity project and I somehow can see something like this:

![Screenshot from 2021-03-29 15-14-33](https://user-images.githubusercontent.com/43362125/201232598-a84c38f6-6b10-459a-9ee7-5b54c22e7ada.png)

If you still meet some problem, I guess you can open an new issue :)

**Comment by ZhihongLiao** [comment]
I still can not open the project like you. Could you tell me how to do like this?

**Comment by C-H-Chien** [comment]
> I still can not open the project like you. Could you tell me how to do like this?

I am sorry it's been a long time since my last try. My laptop is changed and I no longer have this virtual capsule endoscopy. I can try it some time in the coming week.

**Comment by ZhihongLiao** [comment]
Thank you vey much.

**Comment by ZhihongLiao** [comment]
> > 我仍然无法像您一样打开项目。你能告诉我怎么做吗？
> 
> 很抱歉，距离我上次尝试已经很久了。我的笔记本电脑换了，我不再有这个虚拟胶囊内窥镜检查。我可以在下周的某个时候尝试一下。

Thanks.
