### ISSUE TITLE
Magnetodynamics & sofaapapi-unity

### ISSUE THREAD

**Issue by zmyl18641515513** [CapsuleEndoscope/VirtualCapsuleEndoscopy#2]
Hi， Could you please tell me where to install the Magnetodynamics module ? I can't find it in the file you released.
Also, I'd like to know if there are any free resources or alternative plugins for SofaAPAPI-Unity3D to share.

**Comment by inckagan** [comment]
Hi, please refer to Magnetodynamics/Magnetodynamics_v1_0_Documentation.pdf section 2. You don't need to install, you just drag and assign objects into the scene.
