### ISSUE TITLE
How to obtain depth images ground truth?

### ISSUE THREAD

**Issue by wangliangyu-code** [CapsuleEndoscope/VirtualCapsuleEndoscopy#8]
Thank you very much for the Unity project. It would be helpful for my future research.

I am trying to collected my dataset to finish depth estimation task. However, I was confused about how to obtain depth images ground truth in your project for evaluation.

Could you give me a tutorial? Thank you very much!

**Comment by inckagan** [comment]
Hi, AOV Image Sequence should provide you depth maps in Recorder tool. Please check Creating Synthetic Data section.

**Comment by lby53** [comment]
HI,How to convert AOV Image to color depth map?

**Comment by lantudou** [comment]
maybe i have some misunderstanding points, but the generate depth map seems like a reverse depth map.
